### ISSUE TITLE
Can't request trial license after the intial boot-up of the cjoc

### ISSUE THREAD

**Issue by bbrundert** [dillson/jw-workshop#3]
Request for documentation/hint:
Had to restart the cjoc pod manually to actually get the "request trial license" through. Otherwise it failed with a strange error message after you enter your contact information in the web UI.

Resolution:
`jw-workshop$ kubectl delete pod cjoc-0 --namespace=cloudbees`
=> After that, the request for a trial license worked out

**Comment by dillson** [comment]
I have not been able to reproduce this, so I will close this issue
